version: 0.0
os: linux
# copy all files from CodeCommit to app directory
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root    
hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/app_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root

