# Generated by Django 4.1.4 on 2023-10-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('HP', models.PositiveIntegerField()),
                ('img_url', models.URLField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
